import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ProvidesClient } from "@/provides";
import { Navbar } from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";

import "simplebar-react/dist/simplebar.min.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ProvidesClient>
        <body className={cn("antialiased min-h-svh grainy", inter.className)}>
          <Toaster />
          <div>
            <Navbar />
            {children}
          </div>
        </body>
      </ProvidesClient>
    </html>
  );
}
